config/routes.rb
Rails.application.routes.draw do
  resources :characters
  root 'characters#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/attrib.rb
class Attrib < ActiveRecord::Base
  has_many :skills
  has_many :characters, through: :characters_attribs

  def self.method_missing(method_name, *args, &block)
    find_by(name: method_name.to_s.titleize)
  end
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :card_rank
  belongs_to :card_suite

  def to_s
    self.name
  end

  def name
    self.card_rank.name + ' of ' + self.card_suite.name
  end
end

app/models/card_rank.rb
class CardRank < ActiveRecord::Base
end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :ini_min, class_name: 'Card'
  belongs_to :ini_max, class_name: 'Card'
  belongs_to :race
  belongs_to :rank
  belongs_to :character_type
  has_many :attribs, through: :characters_attribs
  has_many :characters_attribs
  has_many :skills, through: :characters_skills
  has_many :characters_skills
  has_and_belongs_to_many :edges
  has_and_belongs_to_many :hindrances
  has_and_belongs_to_many :powers

  attr_accessible :name, :description, :exp, :bennies, :money, :ini_cards, :ini_min_id, :ini_max_id, :race_id, :rank_id, :character_type_id, :edge_ids, :hindrance_ids, :power_ids, :characters_attribs, :skill

  def characters_attrib(attrib)
    self.characters_attribs.select { |character_attrib| character_attrib.id == attrib.id }.first
  end

  def attrib_dice(attrib)
    c_attrib = characters_attrib(attrib)
    if c_attrib
      c_attrib.dice
    else
      Dice.d4
    end
  end

  def characters_skill(skill)
    self.characters_skills.select { |character_skill| character_skill.id == skill.id }.first
  end

  def skill_dice(skill)
    c_skill = characters_skill(skill)
    if c_skill
      c_skill.dice
    else
      Dice.new
    end
  end


end

app/models/character_type.rb
class CharacterType < ActiveRecord::Base
  has_many :characters
  def to_s
    self.name
  end
end

app/models/dice.rb
class Dice < ActiveRecord::Base
  scope :character_sheet, -> { where('number > ? and plus < ?', 3, 5) }

  def self.d3
    find_by(number: 3)
  end

  def self.d4
    find_by(number: 4)
  end

  def self.d6
    find_by(number: 6)
  end

  def self.d8
    find_by(number: 8)
  end

  def self.d10
    find_by(number: 10)
  end

  def self.d12(plus = 0)
    find_by(number: 12, plus: plus)
  end
end

app/models/edge.rb
class Edge < ActiveRecord::Base
  belongs_to :edge_type
  belongs_to :rank
  has_and_belongs_to_many :characters
  has_and_belongs_to_many :modifiers
  has_and_belongs_to_many :requirements

  scope :non_racial, -> { joins(:edge_type).where('edge_types.name != ?', 'Racial') }

  def self.method_missing(method_name, *args, &block)
    find_by(name: method_name.to_s.titleize)
  end

  def add_modifier(modifier)
    if not self.modifiers.include? modifier then self.modifiers << modifier end
  end

  def add_requirement(requirement)
    if not self.requirements.include? requirement then self.requirements << requirement end
  end
end

app/models/edge_type.rb
class EdgeType < ActiveRecord::Base
  has_many :edges
  def to_s
    self.name
  end
end

app/models/hindrance.rb
class Hindrance < ActiveRecord::Base
  belongs_to :hindrance_type
  has_and_belongs_to_many :characters
  has_and_belongs_to_many :modifiers

  scope :non_racial, -> { joins(:hindrance_type).where('hindrance_types.name != ?', 'Racial') }

  def self.method_missing(method_name, *args, &block)
    find_by(name: method_name.to_s.titleize)
  end

  def add_modifier(modifier)
    if not self.modifiers.include? modifier then self.modifiers << modifier end
  end
end

app/models/mod_edge.rb
class ModEdge < ActiveRecord::Base
  has_one :modifier, as: :mod
  belongs_to :edge
end

app/models/mod_power.rb
class ModPower < ActiveRecord::Base
  has_one :modifier, as: :mod
  belongs_to :power
end

app/models/mod_skill.rb
class ModSkill < ActiveRecord::Base
  has_one :modifier, as: :mod
  belongs_to :skill
end

app/models/modifier.rb
class Modifier < ActiveRecord::Base
  belongs_to :mod, polymorphic: true
  has_and_belongs_to_many :edges
  has_and_belongs_to_many :hindrances
  has_and_belongs_to_many :races
end

app/models/mods_pace.rb
class ModsPace < ActiveRecord::Base
  has_one :mod_secondary, as: :mods
end

app/models/power.rb
class Power < ActiveRecord::Base
  belongs_to :power_type
  belongs_to :rank
  has_and_belongs_to_many :characters
  has_and_belongs_to_many :requirements

  def self.method_missing(method_name, *args, &block)
    find_by(name: method_name.to_s.titleize)
  end
end

app/models/race.rb
class Race < ActiveRecord::Base
  has_and_belongs_to_many :modifiers

  def to_s
    self.name
  end

  def self.method_missing(method_name, *args, &block)
    find_by(name: method_name.to_s.titleize)
  end

  def add_modifier(modifier)
    if not self.modifiers.include? modifier then self.modifiers << modifier end
  end
end

app/models/rank.rb
class Rank < ActiveRecord::Base
  has_many :edges
  has_many :powers

  def to_s
    self.name
  end

  def self.method_missing(method_name, *args, &block)
    find_by(name: method_name.to_s.titleize)
  end

end

app/models/req_edge.rb
class ReqEdge < ActiveRecord::Base
  has_one :requirement, as: :req
  belongs_to :edge
end

app/models/req_power.rb
class ReqPower < ActiveRecord::Base
  has_one :requirement, as: :req
  belongs_to :power
end

app/models/req_rank.rb
class ReqRank < ActiveRecord::
  has_one :requirement, as: :req
  belongs_to :rank
end

app/models/req_skill.rb
class ReqSkill < ActiveRecord::Base
  has_one :requirement, as: :req
  belongs_to :skill
  belongs_to :dice
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :attrib
  has_many :characters, through: :characters_skills

  def self.method_missing(method_name, *args, &block)
    find_by(name: method_name.to_s.titleize)
  end
end

app/controllers/characters_controller.rb
class CharactersController < InheritedResources::Base
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>
    <% if @character.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

          <ul>
            <% @character.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div id="card">
    <div id="name">
      <%= f.label :name %>:
      <%= f.text_field :name %>
    </div>
    <div id="race">
      <%= f.label :race_id %>:
      <%= collection_select(:character, :race_id, Race.all, :id, :name, prompt: false)%>
    </div>
    <div id="description">
      <%= f.label 'Description:', class: 'descriptionLabel' %>
      <%= f.text_area :description %>
    </div>
    <div id="exp">
      <%= f.label :exp %>:
      <%= f.number_field :exp %>
    </div>
    <div id="attributes">
      <table>
        <% Attrib.all.each do |attrib| %>
        <tr class="attribute">
          <th>
            <%= attrib.name %>
          </th>
          <td>
            <input type="hidden" name="character[characters_attribs][attrib_id]" value="<%= attrib.id %>" />
            <% Dice.character_sheet.each do |dice| %>
                <input
                  type="radio"
                  name="character[characters_attribs][dice_id]"
                  <% if @character.attrib_dice(attrib).id == dice.id %>checked="checked"<% end %>
                  value="<%= dice.number %>"><img src="<%= image_url "dice/a#{dice.number}.png" %>"/>
                <% if dice.plus != 0 %>+<%= dice.plus %><% end %>
            <% end %>
          </td>
        </tr>
        <div id="skills">
          <% Skill.where(attrib_id: attrib.id).each do |skill| %>
            <tr class="skill">
              <th>
                <%= skill.name %>
              </th>
              <td>
                <% Dice.character_sheet.each do |dice| %>
                  <input
                    type="radio"
                    name="character[skill][<%= skill.id %>][][dice_id]"
                    <% if @character.skill_dice(skill).id == dice.id %>checked="checked"<% end %>
                    value="<%= dice.number %>"><img src="<%= image_url "dice/s#{dice.number}.png" %>" />
                    <% if dice.plus != 0 %>+<%= dice.plus %><% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </div>
        <% end %>
      </table>
    </div>
    <div id="edges">
      <div class="header"><%= f.label 'Edges' %>:</div>
      <%= collection_check_boxes :character, :edge_ids, Edge.non_racial, :id, :name do |e| %>
          <div>
            <span><%= e.check_box %></span>
            <span title="<%= e.object.description %>"><%= e.label %></span>
          </div>
      <% end %>
    </div>
    <div id="hindrances">
      <div class="header"><%= f.label 'Hindrances' %>:</div>
      <%= collection_check_boxes :character, :hindrance_ids, Hindrance.non_racial, :id, :name do |e| %>
          <div>
            <span><%= e.check_box %></span>
            <span title="<%= e.object.description %>"><%= e.label %></span>
          </div>
      <% end %>
    </div>
    <div id="powers">
      <div class="header"><%= f.label 'Powers' %>:</div>
      <%= collection_check_boxes :character, :power_ids, Power.all, :id, :name do |e| %>
          <div>
            <span><%= e.check_box %></span>
            <span title="<%= e.object.description %>"><%= e.label %></span>
          </div>
      <% end %>
    </div>
    <div id="submit">
      <table class="submit">
        <tr>
          <td colspan="2">
            <div class="actions">
              <%= f.submit %>
            </div>
          </td>
        </tr>
      </table>
    </div>
  </div>
<% end %>

app/views/characters/_form2.html.erb
<%= form_for(@character) do |f| %>
    <% if @character.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

          <ul>
            <% @character.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
    <div class="field">
      <%= f.label :exp %><br>
      <%= f.number_field :exp %>
    </div>
    <div class="field">
      <%= f.label :bennies %><br>
      <%= f.number_field :bennies %>
    </div>
    <div class="field">
      <%= f.label :money %><br>
      <%= f.number_field :money %>
    </div>
    <div class="field">
      <%= f.label :ini_cards %><br>
      <%= f.number_field :ini_cards %>
    </div>
    <div class="field">
      <%= f.label :ini_min %><br>
      <%= collection_select(:character, :ini_min_id, Card.all, :id, :name, prompt: false)%>
    </div>
    <div class="field">
      <%= f.label :ini_max %><br>
      <%= collection_select(:character, :ini_max_id, Card.all, :id, :name, prompt: false)%>
    </div>
    <div class="field">
      <%= f.label :race_id %><br>
      <%= collection_select(:character, :race_id, Race.all, :id, :name, prompt: false)%>
    </div>
    <div class="field">
      <%= f.label :rank_id %><br>
      <%= collection_select(:character, :rank_id, Rank.all, :id, :name, prompt: false)%>
    </div>
    <div class="field">
      <%= f.label :character_type_id %><br>
      <%= collection_select(:character, :character_type_id, CharacterType.all, :id, :name, prompt: false)%>
    </div>
    <div class="field">
      <%= f.label 'Edges' %><br>
      <%= collection_check_boxes(:character, :edge_ids, Edge.non_racial, :id, :name)%>
    </div>
    <div class="field">
      <%= f.label 'Hindrances' %><br>
      <%= collection_check_boxes(:character, :hindrance_ids, Hindrance.all, :id, :name)%>
    </div>
    <div class="field">
      <%= f.label 'Powers' %><br>
      <%= collection_check_boxes(:character, :power_ids, Power.all, :id, :name)%>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/characters/_form_scroll.html.erb
<%= form_for(@character) do |f| %>
    <% if @character.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

          <ul>
            <% @character.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div id="card">
    <div id="name">
      <%= f.label :name %>:
      <%= f.text_field :name %>
    </div>
    <div id="race">
      <%= f.label :race_id %>:
      <%= collection_select(:character, :race_id, Race.all, :id, :name, prompt: false)%>
    </div>
    <div id="description">
      <%= f.label 'Description:', class: 'descriptionLabel' %>
      <%= f.text_area :description %>
    </div>
    <div id="exp">
      <%= f.label :exp %>:
      <%= f.number_field :exp %>
    </div>
    <div id="attributes">
      <table>
        <% Attrib.all.each do |attrib| %>
        <tr class="attribute">
          <th>
            <%= attrib.name %>
          </th>
          <td>
            <input type="hidden" name="character[characters_attribs][attrib_id]" value="<%= attrib.id %>" />
            <% Dice.character_sheet.each do |dice| %>
                <input
                  type="radio"
                  name="character[characters_attribs][dice_id]"
                  <% if @character.attrib_dice(attrib).id == dice.id %>checked="checked"<% end %>
                  value="<%= dice.number %>"><img src="<%= image_url "dice/a#{dice.number}.png" %>"/>
                <% if dice.plus != 0 %>+<%= dice.plus %><% end %>
            <% end %>
          </td>
        </tr>
        <div id="skills">
          <% Skill.where(attrib_id: attrib.id).each do |skill| %>
            <tr class="skill">
              <th>
                <%= skill.name %>
              </th>
              <td>
                <% Dice.character_sheet.each do |dice| %>
                  <input
                    type="radio"
                    name="character[skill][<%= skill.id %>][][dice_id]"
                    <% if @character.skill_dice(skill).id == dice.id %>checked="checked"<% end %>
                    value="<%= dice.number %>"><img src="<%= image_url "dice/s#{dice.number}.png" %>" />
                    <% if dice.plus != 0 %>+<%= dice.plus %><% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </div>
        <% end %>
      </table>
    </div>
    <div id="edges">
      <div class="header"><%= f.label 'Edges' %>:</div>
      <%= collection_check_boxes :character, :edge_ids, Edge.non_racial, :id, :name do |e| %>
          <div>
            <span><%= e.check_box %></span>
            <span title="<%= e.object.description %>"><%= e.label %></span>
          </div>
      <% end %>
    </div>
    <div id="hindrances">
      <div class="header"><%= f.label 'Hindrances' %>:</div>
      <%= collection_check_boxes :character, :hindrance_ids, Hindrance.non_racial, :id, :name do |e| %>
          <div>
            <span><%= e.check_box %></span>
            <span title="<%= e.object.description %>"><%= e.label %></span>
          </div>
      <% end %>
    </div>
    <div id="powers">
      <div class="header"><%= f.label 'Powers' %>:</div>
      <%= collection_check_boxes :character, :power_ids, Power.all, :id, :name do |e| %>
          <div>
            <span><%= e.check_box %></span>
            <span title="<%= e.object.description %>"><%= e.label %></span>
          </div>
      <% end %>
    </div>
    <div id="submit">
      <table class="submit">
        <tr>
          <td colspan="2">
            <div class="actions">
              <%= f.submit %>
            </div>
          </td>
        </tr>
      </table>
    </div>
  </div>
<% end %>

app/views/characters/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<h1>Listing characters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Exp</th>
      <th>Bennies</th>
      <th>Money</th>
      <th>Ini cards</th>
      <th>Card</th>
      <th>Card</th>
      <th>Race</th>
      <th>Rank</th>
      <th>Character type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.name %></td>
        <td><%= character.description %></td>
        <td><%= character.exp %></td>
        <td><%= character.bennies %></td>
        <td><%= character.money %></td>
        <td><%= character.ini_cards %></td>
        <td><%= character.ini_min %></td>
        <td><%= character.ini_max %></td>
        <td><%= character.race %></td>
        <td><%= character.rank %></td>
        <td><%= character.character_type %></td>
        <td><%= link_to 'Show', character %></td>
        <td><%= link_to 'Edit', edit_character_path(character) %></td>
        <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @character.description %>
</p>

<p>
  <strong>Exp:</strong>
  <%= @character.exp %>
</p>

<p>
  <strong>Bennies:</strong>
  <%= @character.bennies %>
</p>

<p>
  <strong>Money:</strong>
  <%= @character.money %>
</p>

<p>
  <strong>Ini cards:</strong>
  <%= @character.ini_cards %>
</p>

<p>
  <strong>Ini min:</strong>
  <%= @character.ini_min %>
</p>

<p>
  <strong>Ini max:</strong>
  <%= @character.ini_max %>
</p>

<p>
  <strong>Race:</strong>
  <%= @character.race %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @character.rank %>
</p>

<p>
  <strong>Character type:</strong>
  <%= @character.character_type %>
</p>

<p>
  <strong>Edges:</strong>
  <table>
  <% @character.edges.each do |edge| %>
    <tr>
      <td title="<%= edge.description %>"><%= edge.name %></td>
      <td><%= edge.edge_type %></td>
    </tr>
  <% end %>
  </table>
</p>

<p>
  <table>
    <strong>Hindrances:</strong>
  <% @character.hindrances.each do |hindrance| %>
    <tr>
      <td title="<%= hindrance.description %>"><%= hindrance.name %></td>
      <td><%= hindrance.hindrance_type %></td>
    </tr>
  <% end %>
  </table>
</p>

<p>
  <table>
    <strong>Powers:</strong>
  <% @character.powers.each do |power| %>
    <tr>
      <td title="<%= power.description %>"><%= power.name %></td>
      <td><%= power.power_type %></td>
    </tr>
  <% end %>
  </table>
</p>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>